### ISSUE TITLE
ReadTheDocs - Repository Names

### ISSUE THREAD

**Issue by tkell** [bmcfee/shablona#10]
RTD namespaces `projectname.readthedocs.io` - so we might not be able to push each fork to it.  @bmcfee will look around and see what make sense!

**Comment by bmcfee** [comment]
Summarizing offline conversation:

RTD does not support CI doc builds on forks, so we're going to drop this bit for now.

Instead, we'll do the following:

1) show how to build docs locally with sphinx
2) do a live demonstration of a PR merge, and show the documentation build updating in response
