### ISSUE TITLE
Tutorial outline

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/shablona#2]
- VCS introduction
  - git, github, accounts
  - clone, fork, commit, push, pull
  - branches
  - workflow, code review / pr, don't be a jerk

- Project template
  - testing, implementing simple functionality
  - requirements, packaging

- Documentation style
  - implement docs, build sphinx, etc
  - software licensing

- Tour of ecosystem
  - jupyter
  - numpy, scipy, matplotlib
  - librosa
  - mir_eval
  - jams
  - music21, prettymidi
  - soundfile, pyaudio (if time)

- Where next?
  - musicinformationretrieval.com
  - software carpentry
  - chosealicense.com
  - don't be a jerk on the internet

**Comment by tkell** [comment]
- Done the VCS intro!

**Comment by tkell** [comment]
- Done Docs and testing!

**Comment by tkell** [comment]
@bmcfee, I envisioned a section that goes over the layout of a package, and why it is done that way, maybe as Part 4 of the things I have written?

**Comment by bmcfee** [comment]
SGTM.  Do you have time to sync on wednesday morning about some of this stuff?

**Comment by tkell** [comment]
Hopefully yes, will send you a calendar.

**Comment by tkell** [comment]
- Done a pass at Ecosystem, may need more words depending on how we want to run that section.

**Comment by tkell** [comment]
- Done Next Steps!
