### ISSUE TITLE
Pre-boot test script

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/shablona#3]
Distribute a script that makes sure that git and anaconda are installed and working

**Comment by tkell** [comment]
Did you have in mind a thing that checked version / exit codes, or just the below?

```
git --version
python --version # should be 3.6 or higher!
conda --version
```

**Comment by tkell** [comment]
Do we also want to ask people to set up their accounts (github, travis, readthedocs, etc?) before they arrive?

**Comment by tkell** [comment]
As per our call:  Run python, check imports for numpy, scipy, `python -e import <blah>`

**Comment by tkell** [comment]
@bmcfee, rough in https://github.com/bmcfee/shablona/pull/12, for your approval

**Comment by tkell** [comment]
Done in #12!
