### ISSUE TITLE
USB sticks with requirements

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/shablona#4]
- anaconda
- git
on all platforms

**Comment by bmcfee** [comment]
and python???

**Comment by tkell** [comment]
![screen shot 2018-08-08 at 14 19 00](https://user-images.githubusercontent.com/263128/43856259-026f7b2c-9b16-11e8-800a-ca79f29ce7cf.png)

Will go hunting for 4-6 USB keys.

**Comment by tkell** [comment]
Only got 3, but calling this done anyways, cc @bmcfee – lmk if you want other installers there.
