### ISSUE TITLE
windows issues

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/shablona#5]
- need bash
- can we leverage existing github setup / tutorials for windows users?

**Comment by bmcfee** [comment]
possibly make?

**Comment by bmcfee** [comment]
gitbash?

**Comment by tkell** [comment]
- Looks like this is the Official Way:  https://docs.microsoft.com/en-us/windows/wsl/install-win10 - even gets you access to `apt`
- Looks like Conda will work:  https://joshpeng.github.io/post/wsl/
- Looks like git works: 
 https://www.reddit.com/r/webdev/comments/6dinxm/can_you_run_git_in_bashwsl_bash_on_ubuntu_on/

**Comment by tkell** [comment]
So @bmcfee, it looks like if they have WSL, we should be OK.  Do we have a way of contacting our people to ask if they're on Windows and point them towards this?

**Comment by tkell** [comment]
Send out a google form for folks, including:  system, experience level, etc.

**Comment by tkell** [comment]
Thor to look into "Bash for Windows" vs WSL – are they the same thing?  Are there any other alternatives out there (git bash, etc)

**Comment by tkell** [comment]
@bmcfee, a heavier google suggests that WSL is the best and correct answer.  

Other semi-alternatives are git bash which is only git, and then cygwin and then this v. reputable thing: http://win-bash.sourceforge.net.

Or we try to make stuff work in PowerShell, but I think that WSL is for sure the way to go.

**Comment by tkell** [comment]
Hopefully dealt with by mailing the list!
