### ISSUE TITLE
Settings for Webpage

### ISSUE THREAD

**Issue by tkell** [bmcfee/shablona#6]
@bmcfee, it looks like you need to go to Settings and throw some switches to enable things:  https://pages.github.com/

**Comment by tkell** [comment]
ping @bmcfee again!  I think you need to make the `gh-pages` branch, and select that as the source in `Settings`?  That is based on https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by bmcfee** [comment]
ok, should be done now.  it's currently hosting at http://bmcfee.github.io/shablona , but we can move that once the content is stable.

**Comment by tkell** [comment]
🚀 , will try to start getting content in.
